name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
        bump_type:
          description: 'Version bump type'
          required: true
          default: 'patch'
          type: choice
          options:
            - major
            - minor
            - patch

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Bump version and create tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.bump_type }}
          TAG_PREFIX: v
          VERBOSE: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag.outputs.new_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.tag.outputs.new_tag }}
            type=semver,pattern={{major}},value=${{ steps.tag.outputs.new_tag }}

      - name: Build and push Docker image
        if: steps.tag.outputs.new_tag != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
env:
  GO_VERSION: "1.24"
  REGISTRY: ghcr.io
